### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Stroketon**

### CODE REVIEW

**Comment by vanility0001** [comment]
wait but dont u have blush still added

**Comment by environment-dev** [comment]
Why do you care about who I have added? 



~ environment

**Comment by vanility0001** [comment]
cuz u shouldnt keep talking to him after what happened (lolz)

~ vanility

**Comment by environment-dev** [comment]
I don't exactly understand why I shouldn't talk to my friends? 
Unless you have a valid reason, I will not stop talking to him


~ environment

**Comment by Stroketon** [comment]
Define grooming my guy

**Comment by vanility0001** [comment]
Define grooming my guy

**Comment by Stroketon** [comment]
Hewwo!
am gwad u chose to hewp out my pwoject. Howevew, me wiww point out a few things that shouwd be changed because dey do not have twuth to them.
 
take a wook at wines 2,3 and 5 in commit 895bb74. These wines aww contain fawse info.
 
pwease fix these issue and me wiww gwadwy mewge dis puww wequest!

~ enviwonment

ps: why did u steaw my joke wow

**Comment by Stroketon** [comment]
Child grooming is befriending and establishing an emotional connection with a child,

**Comment by Stroketon** [comment]
I will not do further damage i just wanna know

**Comment by Stroketon** [comment]
The only reason i wanted to fuck you up as you were annoying and preventing you from being a astral owner

**Comment by aspectiscool** [comment]
these nuts are well

**Comment by Stroketon** [comment]
And plus you should live in skid row in LA

**Comment by Stroketon** [comment]
mentally ill fag

**Comment by environment-dev** [comment]
That's even worse?
You have questioned out people who I've friended.
You might think you are smart as fuck, but I know you. 
All your doing is digging your self deeper. You have basically just admitted that you don't care about the """grooming""" and just wanted to fuck me up. You have real mental problems.

~ environment

**Comment by Stroketon** [comment]
i do still care but i wasn't that sure

**Comment by environment-dev** [comment]
I'd seek mental care if I was you.

BTW, I live in SF not LA.
~ environment

**Comment by Stroketon** [comment]
you were the reason i went "mental"

**Comment by environment-dev** [comment]
Then you need real help. I believe I've said what you need to hear. If you can get "mental" from internet drama then you require mental help. Anyways, at the end of they day, You are a shit person and you know it. You clearly have anger management issue, little Israel kid. 

~ environment

**Comment by environment-dev** [comment]
Nonono. That's not right. Where is your anger fueled response?

~ environment

**Comment by Stroketon** [comment]
Talked with you enough :)

**Pull request closed without merging**
